### ISSUE TITLE
`git remote update` stuck on https url

### ISSUE THREAD

**Issue by ethanyoung** [anz-bank/go-slides#100]
When I was running these two commands:

https://github.com/anz-bank/go-slides/blob/e8644c129cc3024c1f4777db929d4acb5c14fdf9/content/gocourse-2019-05-melbourne.slide#L557-L558

`git remote update` will output:

```
Fetching origin
Fetching upstream
fatal: unable to access 'https://github.com/anz-bank/go-course.git/': Operation timed out after 300031 milliseconds with 0 out of 0 bytes received
error: Could not fetch upstream
```

Using the SSH url `git@github.com:ethanyoung/go-course.git` for the upstream can solve this problem.

**Comment by anzboi** [comment]
I was unable to reproduce this on my machine. Can you send me the url for your fork of the repo.

**Comment by ethanyoung** [comment]
My repo https://github.com/ethanyoung/go-course

I've found the reason. I was using SSH to `git clone` my own repo...

If I use HTTPS to `git clone` (as written in the slides) then everything would be fine.

**Comment by anzboi** [comment]
Did this work? Authentication used with one remote should not affect authentication with others, although I can see how the method used to do the initial clone might affect subsequent remotes, if so, we'll need to change the instructions based on authentication method used.

**Comment by ethanyoung** [comment]
Yep, it just worked on my machine. The instructions are correct.
