### ISSUE TITLE
♻️Eng-edu: restructure & rename repo 

### ISSUE THREAD

**Issue by juliaogris** [anz-bank/go-slides#28]
Rework this repo to become a generic ANZ engineering education location for slides.

- [ ] Rename repo from `go-slides` to `slides` or `anz-slides` or similar
- [ ] Move everything go-training specific into `content/gotraining/` including `pingserver`
- [ ] Use generic GCP project (`anztraining` and `anzedu` have already been acquired by @juliaogris)
- [ ] Use generic short URL for training location `edu.anz` or similar would be cool
- [ ] Move `go present` files (top level `*.go`) into `tool/` or `present/`

**Comment by camscale** [comment]
I'd like to see a restructure that puts the go presentation code one level deeper. The content should be front and centre in this repo. there is also other content in the repo that should also go into a training-specific directory (like pingserver).

**Comment by juliaogris** [comment]
All agreed @camh-anz and issue description updated accordingly.

**Comment by juliaogris** [comment]
Closing this for now until we actually decide to put more, non-Go content in this framework.
