### ISSUE TITLE
Create lab directories on go-training

### ISSUE THREAD

**Issue by juliaogris** [anz-bank/go-slides#57]
`NN_lab_name` for : 
- Lab 1 - Fibonacci
- Lab 2 - Bubble sort
- Lab 3 - Letter frequency
- Lab 4 - Numeronym
- Lab 5 - Stringer
- Lab 6 - CRUD puppy with interface
- Lab 7 - Errors
- Lab 8 - Project Layout
- Lab 9 - JSON puppy
- Lab 10 - Puppy REST
- Lab 11 - Puppy Notifications

**Comment by juliaogris** [comment]
Consider copying [collated assignments gist](https://gist.github.com/juliaogris/5777baa1c2cfab7e5b57635df0379549) here

**Comment by juliaogris** [comment]
Review PR checklist on README.md.

**Comment by camscale** [comment]
The collated assignments gist could be split into separate README.md files for each lab, and that file can be the placeholder that keeps the directory in git (you cannot have empty directories in a git repo).

**Comment by camscale** [comment]
The actual directory names to use can be found in the gist for each lab.
